### ISSUE TITLE
Client install successfully but shows error while I run the command. 

### ISSUE THREAD

**Issue by jaidevjoshi83** [IGS/portal_client#7]
Command "portal_client --help" rais this error... I tried to install this tool on three different Linux machine, (two fedora, and one Ubuntu ) it shows error on all the machines. 
 
[Traceback (most recent call last):
  File "/home/joshij/anaconda2/envs/jay/bin/portal_client", line 4, in <module>
    __import__('pkg_resources').run_script('portal-client==1.4.4', 'portal_client')
  File "/home/joshij/anaconda2/envs/jay/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/joshij/anaconda2/envs/jay/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(script_code, namespace, namespace)
  File "/home/joshij/anaconda2/envs/jay/lib/python2.7/site-packages/portal_client-1.4.4-py2.7.egg/EGG-INFO/scripts/portal_client", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/portal_client.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/manifest_processor.py", line 11, in <module>
  File "/home/joshij/anaconda2/envs/jay/lib/python2.7/site-packages/portal_client-1.4.4-py2.7.egg/portal_http.py", line 120
    print("\r{0}".format(status), end="")
                                    ^
SyntaxError: invalid syntax](url)

**Comment by victor73** [comment]
I believe this is due to a python compatibility problem. If you can, please try to install into a python3 environment instead of python 2.7. I will adjust the installation documentation to make it more clear than Python 3 is required.

**Comment by jaidevjoshi83** [comment]
> I believe this is due to a python compatibility problem. If you can, please try to install into a python3 environment instead of python 2.7. I will adjust the installation documentation to make it more clear than Python 3 is required.
